### PR TITLE
show git tags if any

### PR DESCRIPTION
**Pull request by zztalker**
Without change tags not shown (because return happen earlier).
With change tags shown if exists.

### CODE REVIEW

**Comment by leo150** [comment]
bump

**Comment by zztalker** [comment]
@tommyknows @bobthecow Could you take a look?

**Comment by bobthecow** [comment]
Heh. Sorry about that, somehow I completely missed when this was opened 😬

**Comment by bobthecow** [comment]
Okay so it seems like this changes it to always show a tag _and_ either a branch or commit ref. I'm not sure I love this, to be honest. In the cases where you're looking at a tag that's not the current branch head, showing the commit feels like it'll just add unnecessary noise.

**Comment by zztalker** [comment]
> Okay so it seems like this changes it to always show a tag _and_ either a branch or commit ref. I'm not sure I love this, to be honest. In the cases where you're looking at a tag that's not the current branch head, showing the commit feels like it'll just add unnecessary noise.

We can make it a configurable behavior.  As for me, it adds not much noise, but useful. 

Screenshot 2023-06-29 at 11 05 06

**Comment by bobthecow** [comment]
no, that makes sense. 

i'm specifically talking about the case where you check out a previous tag, which isn't a branch HEAD. previously, it would show the tag:

Screenshot 2023-06-29 at 9 14 32 AM

now it shows the tag and the commit:

Screenshot 2023-06-29 at 9 16 26 AM

the latter is just noise, IMO.

**Pull request merged**
