### PR TITLE
Add option to disable git stash flagging

### PR DESCRIPTION
**Pull request by caesar**
Adds the option requested in #37.

If you prefer not to add new options I understand, but this would fix my main annoyance with bobthefish so I'd love it if it could get in! :-)

As you can see I have used the same mechanism that you had used with the `$theme_display_git_untracked` option.

Any comments or changes you would like, let me know.

### CODE REVIEW

**Comment by bobthecow** [comment]
The reason `$theme_display_git_untracked` exists is entirely performance related (see oh-my-fish/oh-my-fish-legacy#434).

In general, I prefer not to add too many options… bobthefish is opinionated about what makes a good prompt, and that's part of the reason people think it's a good prompt :)

So is there a way we can solve your main annoyance whilst still being opinionated about it? What if, instead of an option to disable it, there were an option to make it less annoying? Maybe just the `$` but not change the color to orange?

**Comment by bobthecow** [comment]
In fact, almost all of the options exist for performance reasons. If you never use {git,hg,worktrees,vagrant,virtualenv,ruby,vi mode}, then disabling them makes everything a _lot_ faster. A handful of the options are opt-in and disabled by default — hg, vagrant, git worktrees, etc — because they're less common and/or a lot slower to enable by default. Otherwise, bobthefish tries to do things "right" rather than "configurable" :P

**Comment by caesar** [comment]
Yep, I understand that and do see the value in being opinionated rather than giving too many options.

Though I would prefer personally to see no indication of the existence of stashes, I could live with showing the $ without not changing the colour; if you feel that would be a good solution.

As a matter of fact, incidentally, checking for stashes _does_ of course have a performance cost, even if it's not huge.

**Comment by caesar** [comment]
As a matter of fact all the colours seem a bit odd to me. I'd say the time the colour _should_ change, but doesn't, is when you have unstaged changes.

I'd go
- unstaged changes -> red
- staged changes -> yellow/orange
- commited -> green

Or does this not make sense?

(I realise this isn't really directly related to the current pull request. Sorry.)

**Comment by bobthecow** [comment]
Unstaged changes are red. Staged changes are _also_ red, though, and I could see a case for changing the color on them to orange or something :)

I do think stashed is important, but maybe not color-change-important. What if it was these flags:

* untracked: `...`
* unstaged: `*`
* staged: `~`
* stashed: `$`

… and these colors:

* anything unstaged: `red`
* else if anything staged: `orange`
* else: `green`

?

**Comment by bobthecow** [comment]
> (I realise this isn't really directly related to the current pull request. Sorry.)

This is directly related. It's us working out how to solve the intent of this pull request, even if it's not with the code from this pull request :)

**Comment by caesar** [comment]
Yes, that makes sense to me.

I was going to comment that I am not seeing a colour change for unstaged changes, but then I realised that the I was really talking about _untracked_ files. I hadn't really thought of this as a different case to (other) unstaged changes.
So that raises the question, should untracked files also cause the prompt to go orange? It feels more natural to me, but I don't know if it's actually better or not now I think about it.

For reference this screenshot seems to show all the variations at the moment, other than stashes.
screen shot 2016-05-17 at 13 18 31

**Comment by bobthecow** [comment]
Untracked files intentionally don't change the color. I feel like a good rule of thumb for a color change is "if I do `git reset --hard` will I lose anything?

**Comment by caesar** [comment]
Okay, maybe that makes sense. I don't have a strong opinion on that one.

Just sent a PR for the new behaviour discussed here. Let's continue the discussion at #43.

**Comment by bobthecow** [comment]
sgtm

**Pull request closed without merging**
