### PR TITLE
Add Gruvbox Theme

### PR DESCRIPTION
**Pull request by Jguer**
Based on [Gruvbox](https://github.com/morhetz/gruvbox-contrib) by morhetz and following the style of the airline theme "Gruvbox".
screenshot from 2016-08-22 02-52-23

### CODE REVIEW

**Comment by bobthecow** [comment]
Looking good!

It would be a bit more true to both bobthefish and gruvbox to use `bg1` or `bg2` for the project path segment (with `fg3` maybe?).

**Comment by Jguer** [comment]
Probably, I'm going to try it. I was using path with the same color as vi_mode_default but then decided to try vi_mode_insert (since I am using emacs mode and by default everything is insert).

Will come back with results.

**Comment by Jguer** [comment]
bg1 with fg2 keeps gruvbox's washed out appearance well

bg1 - fg2
screenshot from 2016-08-22 12-02-25

Added new bg from gruvbox pallete (3c3836) that sits between bg1 and bg2 paired with fg3
screenshot from 2016-08-22 12-11-55

Airline for comparison
screenshot from 2016-08-22 12-14-06

**Comment by Jguer** [comment]
bg1-fg2 (current commit) with the correct gruvbox background
save

**Comment by bobthecow** [comment]
That looks a lot better, thanks!

**Pull request merged**
