### PR TITLE
Fixing desk prompt

### PR DESCRIPTION
**Pull request by remche**
Desk prompt is broken by 5acaae3, here is the fix.

### CODE REVIEW

**Comment by bobthecow** [comment]
Oh no! It was a bad merge. I'm sorry :( 

Do you mind resolving the conflicts so I can merge? Otherwise I'm happy to apply this fix this evening.

**Comment by remche** [comment]
Hum, I can't see any conflict, am I missing something ?

**Comment by bobthecow** [comment]
screen shot 2018-04-12 at 12 14 58 am

¯\_(ツ)_/¯

**Comment by remche** [comment]
toto

that's odd… will try to close this one and do a new one…

**Pull request closed without merging**
