### PR TITLE
Add gruvbox light theme

### PR DESCRIPTION
**Pull request by josselinauguste**
Add gruvbox light theme

### CODE REVIEW

**Comment by bobthecow** [comment]
Thanks! Do you mind posting screenshots of `bobthefish_display_colors` for both the light and dark variants?

**Comment by josselinauguste** [comment]
Yes of course I can, try to do it ASAP!

**Comment by josselinauguste** [comment]
Just added the screenshot for gruvbox-light, sadly it would not be easy to make one for gruvbox as it would imply overriding all my term colors.

**Comment by josselinauguste** [comment]
Just fixed the conflict with master 👍 It is now ready to be reviewed

**Pull request merged**
