### PR TITLE
Replace some color constants with existing variables

### PR DESCRIPTION
**Pull request by LambdaLord**

### CODE REVIEW

**Comment by bobthecow** [comment]
:+1:

**Comment by bobthecow** [comment]
Um. FFF definitely isn't dark blue.

**Comment by LambdaLord** [comment]
Sorry, I didn't mean to push those yet. Still rather new to git.

**Comment by bobthecow** [comment]
… but it's still not blue. fff is white :)

**Comment by LambdaLord** [comment]
Gah! This is what happens when your crappy hex color lookup pads zeros the front.

**Pull request merged**
