### PR TITLE
Add option to hide cmd duration

### PR DESCRIPTION
**Pull request by zaclimon**
In case there are people who want to keep their terminal "clean".

### CODE REVIEW

**Comment by bobthecow** [comment]
To disable the greeting, the fishier thing to do is write your own `fish_greeting` function.

**Comment by zaclimon** [comment]
Ohh okk then. is the CMD duration option fishy enough?

**Comment by bobthecow** [comment]
Yeah, I think so :)

Let's change it to `theme_display_cmd_duration`, and add it to the list in the readme?

**Comment by zaclimon** [comment]
This should look fine now. :)

**Comment by bobthecow** [comment]
Great, thanks!

**Pull request merged**
